### ISSUE TITLE
DATETIME column type maps to DateTime64(3)

### ISSUE THREAD

**Issue by AlmostIvanSidorov** [Altinity/clickhouse-sink-connector#89] opened 2022-09-19 14:36 UTC
[2022-09-16](https://hub.docker.com/layers/altinity/clickhouse-sink-connector/2022-09-16/images/sha256-311a151669ef4a69e3343659525bf39d9356698625c50fc53d02fb0db62043ec?context=explore) sink-connector maps MySQL DATETIME column type to DateTime64(3) column type in ClickHouse. (Expected mapping type is DateTime)

**Comment by aadant** [comment] 2022-09-22 03:49
Duplicate of https://github.com/Altinity/clickhouse-sink-connector/issues/75

**Closed by aadant** 2022-09-22 03:49 UTC
Labels: duplicate
